language: android

sudo: false

jdk:
  - oraclejdk7

android:
  components:
    - platform-tools
    - tools
    - android-23
    - build-tools-23.0.2
    - extra-google-m2repository
    - extra-android-m2repository

script: ./gradlew build check --stacktrace
