language: android
jdk:
  - oraclejdk8
android:
  components:
    - tools
    - tools # TODO https://github.com/travis-ci/travis-ci/issues/6193
    - platform-tools
    - build-tools-24.0.3
    - android-24
    - extra-android-m2repository
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
script: "./gradlew $TASK"
env:
    - TASK="lintFlavorDandelionDebug"
    - TASK="build check --stacktrace"

branches:
  except:
  - l10n_master
  - l10n_master2
  - crowdin
notifications:
  webhooks:
    urls:
      - "https://webhooks.gitter.im/e/e462044d3105a7bb4b4f"
      - "https://scalar.vector.im/api/neb/services/hooks/dHJhdmlzLWNpLyU0MGdzYW50bmVyJTNBbWF0cml4Lm9yZy8lMjFNUERTYURTaVBMZXdSQXBxa24lM0FtYXRyaXgub3Jn"
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

after_success:
  - bash <(curl -s https://codecov.io/bash)
