files:
  - 
    source: '/app/src/main/res/values/strings*.xml'
    translation: '/app/src/main/res/values-%android_code%/%original_file_name%'
    languages_mapping:
      android_code:
        sv-SE: sv
        es-ES: es
        ml-IN: ml
        pt-PT: pt
        "no": 'no'
        de: de
        tr: tr
        ca: ca
        ru: ru
        pl: pl
        nl: nl
        ja: ja
        it: it
        hu: hu
        hi: hi
        fr: fr
        el: el
        cs: cs
