files:
  - 
    source: '/app/src/main/res/values/strings*.xml'
    translation: '/app/src/main/res/values-%android_code%/%original_file_name%'
    languages_mapping:
      android_code:
        ml-IN: ml 	# Malayalam
        sv-SE: sv 	# Swedish
        es-ES: es 	# Espanol
        de: de 		# German
        ru: ru 		# Russian
        pl: pl 		# Polish
        ja: ja 		# Japanese
        it: it 		# Italian
        fr: fr 		# French
        kn: kn 		# Kannada (Asian)
#       hu: hu 		# Hungarian
#       hi: hi 		# Hindi
#       nl: nl 		# Dutch
#       el: el 		# Greel
#       cs: cs 		# Czeck
#       "no": 'no' 	# Norwegian
#       tr: tr 		# Turkish
#       ca: ca 		# Catalan
#       pt-PT: pt 	# Portugese
